### ISSUE TITLE
Deployment process

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/deployment#4]
1. checkout qooxdoo repo
2. checkout compiler repo
3. mount framework dir into compiler node_modules/@qooxdoo/framework/source
4. compile the compiler 
5. run compiler tests
6. link the compiler to $WORKING_ABS_DIR/bin/qx
7. compile the server framework with the new compiled compiler.
8. checkout apiviewer
9. compile apiviewer
10. run tests with apiviewer
11. do step 7 to 9 with each pkg we like
12. generate version number for framework
13. compile framework
14. publish  NPM package @qooxdoo/framework
15. publish NPM package @qooxdoo/server
16. publish CDN package qooxdoo. 
17. generate version number for the compiler
18. remove devDependencies from compiler package.json to avoid circular reference to @qooxdoo/compiler
19. add framework version number to @qooxdoo/framework dependency
20. publish NPM package @qooxdoo/compiler

**Comment by cboulanger** [comment]
Once we have sorted this out, we should document it in the deployment repo, since it is quite a complex process that one has to wrap one's head around -> so that the others understand what is going on.

**Comment by hkollmann** [comment]
It's working now
