### ISSUE TITLE
Wrong version in compiler Manifest.json

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/deployment#6]
The `info.version` key in the compiler's `Manifest.json` doesn't seem to get updated before NPM release. For example, in the current NPM module `v1.0.0-beta-20200928-1855`, the version info in the Manifest is `"version": "1.0.0-beta-20200812-2003"`. 

There is [code to update the Manifest file](https://github.com/qooxdoo/deployment/blob/master/deployer.sh#L334) but somehow this doesn't seem to work. 

Any idea, @johnspackman , why this might be?

**Comment by hkollmann** [comment]
Just do npm install @qooxdoo/compiler:

"info": {
    "name": "@qooxdoo/qooxdoo-compiler",
    "summary": "The new fast JavaScript Compiler for Qooxdoo",
    "description": "The Qooxdoo-Compiler is the new compiler and command line interface for Qooxdoo applications. It is written in Node.JS Javascript and replaces the Python-based generator.",
    "homepage": "https://github.com/qooxdoo/qooxdoo-compiler",
    "license": "MIT license",
    "authors": [
      {
        "name": "John Spackman (johnspackman)",
        "email": "john.spackman@zenesis.com"
      },
      {
        "name": "Christian Boulanger (cboulanger)",
        "email": "info@bibliograph.org"
      },
      {
        "name": "Henner Kollmann (hkollmann)",
        "email": "Henner.Kollmann.gmx.de"
      }
    ],
    "version": "1.0.0-beta-20200928-1855"
  },
  
Which is correct

**Comment by hkollmann** [comment]
Can't be reproduced
